### ISSUE TITLE
Python TUI frontend

### ISSUE THREAD

**Issue by KerstinGreifensteiner** [malviguys/frontendcli#1]
- [x] Implement primitive domains
- [x] Implement entities
- [x] Menu
- [x] App
- [ ] Implement communications with backend
- [x] Add lesson
- [x] Remove lesson
- [x] Book lesson
- [x] Cancel a booking
- [ ] Find lesson by parameters
- [ ] Check how many people attending at a specific lesson

**Comment by Claudiocli** [comment]
- [ ] Implement communications with backend
- [x] Add lesson
- [x] Remove lesson
- [x] Book lesson
- [x] Cancel a booking
- [ ] Find lesson by parameters
- [ ] Check how many people attending at a specific lesson
